### ISSUE TITLE
Feature Request: Multiselect for scan area in instance

### ISSUE THREAD

**Issue by bschultz** [versx/ChuckDeviceController#27]
Can we turn the scan area into a multiselect and assign multiple scan areas to an instance?

**Comment by versx** [comment]
Yeah we could, I can't think of any restrictions/huge changes with changing it off the top of my head. I'll try working on this today. (unless someone else wants to start/do it - that's cool too)

**Comment by versx** [comment]
I guess we should add multiple geofence support for webhooks too?

**Comment by versx** [comment]
Only issue with changing it to support multiple geofences is if you rename a geofence then since it's a json column you lose support for constraints and auto-update of names. If you rename a geofence then instances that reference that geofence will need to be updated manually, or we could use relational tables.
